services:
  backend:
    build: ./subtitle-translator-back
    container_name: subtranslator-backend
    ports:
      - "5001:5001"
    volumes:
      - /mnt/media:/mnt/media
    environment:
      - OLLAMA_HOST=http://192.168.0.6:11434
    restart: unless-stopped
  frontend:
    build: ./subtitle-translator-front
    container_name: subtranslator-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
